[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "./gradlew bootJar"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
sleepApplication = false
numReplicas = 1

[service]
autoStart = true

[scaling]
min = 1
max = 1 